### ISSUE TITLE
Convex hulls from torso laser in the /ed/map ,

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/ed_navigation#2]
Amigo therefore cannot navigate when it has grasped something large. This needs to be checked; either in the costmap integration or this one.

**Comment by Rayman** [comment]
Is this still an issue?

**Comment by MatthijsBurgh** [comment]
This needs some extra attention before the tournaments.

**Comment by MatthijsBurgh** [comment]
Torso laser removed from costmaps. So solved I would say?!

**Comment by MatthijsBurgh** [comment]
@reinzor status?

**Comment by MatthijsBurgh** [comment]
ping

**Comment by reinzor** [comment]
No idea

**Comment by MatthijsBurgh** [comment]
Convex hulls are not in the ed/map. And the torso laser is also removed from the costmap. So not an issue anymore.
